Adding a more secure default cipher
Jsondb/jsondb-core pull request #20
Opened 2019-06-20 09:43 UTC by rzwitserloot

A few concerns:

1. I kept DefaultAESCBCCipher, but deprecated it. The intent is that users of the library now know to transition away from it, but this won't leave their dbs encrypted with this deprecated cipher unaccessible.
2. I left almost all of the tests using the now deprecated AESCBC; to remake these tests, the db files in src/test/resources need to be re-created.
3. I named the name cipher `Default1Cipher` to cover a few intents: Let's not hardcode implementation details that aren't particularly relevant into this name, and also we now adhere to modern java naming conventions (which dictate `DefaultAesCbcCipher`). The `1` in the name is to leave room for a new default which is not compatible with this one.
4. The IV is now randomly generated and returned as part of the ciphertext. That does mean that the transition from plaintext to ciphertext is __NOT__ deterministic (run the same code twice in a row and different ciphertext ensues; this is more or less the point, as otherwise you could at least recognize that the same data has been encrypted with the same key!), and that requires some reworks on the test code.
5. The basic crypto test _HAS_ been updated, but almost all the other tests also use crypto and need an update.

2019-06-20 09:43 UTC, rzwitserloot commented
See also issue #19

2019-06-20 09:44 UTC, rzwitserloot commented
CONTEXT: Not a user of jsondb but was discussing this with @yawkat on freenode ##java and wanted to investigate GCM mode.

2019-06-20 09:47 UTC, rzwitserloot commented
The song and dance routine with the bytebuffers is to avoid 1 additional byte array creation whose size is related to the size of the cipher/plaintext. However, the API of the ICipher interface (turning strings into Base64 strings) is fundamentally at odds with doing this efficiently. I've decided not to refactor the API, that felt a little drastic :)

Given that performance in the face of larger texts is already hard to accomplish, perhaps it was overkill.

2019-06-20 09:51 UTC, yawkat requested changes

2019-06-20 09:51 UTC, yawkat commented on src/main/java/io/jsondb/crypto/Default1Cipher.java
> +      enc.init(Cipher.ENCRYPT_MODE, key, new GCMParameterSpec(IV_SIZE * 8, iv));
The first parameter to GCMParameterSpec should be the tag length, not the IV length. Tag length should be 128 bits

2019-06-20 09:51 UTC, yawkat commented on src/main/java/io/jsondb/crypto/Default1Cipher.java
> +  private static final int IV_SIZE = 12;
16 byte / 128 bit IV would be better

2019-06-20 09:57 UTC, sonOfRa requested changes

2019-06-20 09:57 UTC, sonOfRa commented on src/main/java/io/jsondb/crypto/Default1Cipher.java
> +    } catch (BadPaddingException | InvalidAlgorithmParameterException e) {
On decryption with AEAD modes, one needs to handle  AEADBadTagException. This is thrown when the tag is invalid (which means the ciphertext was tampered with in some form, or the decryption key may have been incorrect).

AEADBadTagException is a subclass of BadPaddingException, but I think it should be handled separately and explicitly.

2019-06-20 10:27 UTC, yawkat approved these changes

2019-06-20 17:18 UTC, FarooqKhan commented
Thanks for doing this, I will spend some time on this over the weekend, and merge it it in.

2019-09-23 17:41 UTC, FarooqKhan commented
Just wanted to update here, i do plan to review this and merge it however last several months i have been totally swamped i hope to do this sometime in October

2019-10-12 16:22 UTC, FarooqKhan approved these changes

2019-10-12 16:22 UTC, FarooqKhan commented
@rzwitserloot Thank you for doing this, please accept my apologies for the delay, i have been seriously crunched these last few months.

2019-10-12 16:23 UTC, merged